
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Mar 28 12:39:01 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Symbol {
  /* terminals */
  public static final int TIMES = 12;
  public static final int LT = 4;
  public static final int NE = 9;
  public static final int SEMICOLON = 14;
  public static final int PLUS = 10;
  public static final int RPAREN = 18;
  public static final int THEN = 28;
  public static final int WHILE = 30;
  public static final int CALL = 21;
  public static final int SLASH = 13;
  public static final int END = 24;
  public static final int PERIOD = 15;
  public static final int IF = 25;
  public static final int LPAREN = 17;
  public static final int GT = 6;
  public static final int ODD = 26;
  public static final int ID = 2;
  public static final int LE = 5;
  public static final int DO = 23;
  public static final int BEGIN = 20;
  public static final int COMMA = 16;
  public static final int EOF = 0;
  public static final int GE = 7;
  public static final int MINUS = 11;
  public static final int CONST = 22;
  public static final int error = 1;
  public static final int PROC = 27;
  public static final int ASSIGN = 19;
  public static final int EQ = 8;
  public static final int INTEGER = 3;
  public static final int VAR = 29;
}

