
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Tue Mar 27 15:01:45 CST 2018
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class tinyjavasymbol {
  /* terminals */
  public static final int CONST = 22;
  public static final int GE = 7;
  public static final int SLASH = 13;
  public static final int PERIOD = 15;
  public static final int COMMENT = 34;
  public static final int ARGS = 45;
  public static final int INTEGER = 3;
  public static final int LPAREN = 17;
  public static final int INT = 43;
  public static final int PRINTLN = 49;
  public static final int OUT = 48;
  public static final int MINUS = 11;
  public static final int BAR = 50;
  public static final int STATIC = 37;
  public static final int RPAREN = 18;
  public static final int SEMICOLON = 14;
  public static final int LT = 4;
  public static final int IN = 59;
  public static final int COMMA = 16;
  public static final int CALL = 21;
  public static final int CLASS = 33;
  public static final int BEGIN = 20;
  public static final int NEXTINT = 53;
  public static final int PLUS = 10;
  public static final int MAIN = 39;
  public static final int ASSIGN = 19;
  public static final int IF = 25;
  public static final int THIS = 56;
  public static final int ID = 2;
  public static final int LE = 5;
  public static final int BOOLEAN = 57;
  public static final int EOF = 0;
  public static final int RETURN = 51;
  public static final int SYSTEM = 47;
  public static final int FACTO = 54;
  public static final int NEW = 46;
  public static final int error = 1;
  public static final int LCURLY = 41;
  public static final int SCANNER = 52;
  public static final int VOID = 38;
  public static final int EQ = 8;
  public static final int RCURLY = 42;
  public static final int IMPORT = 35;
  public static final int TIMES = 12;
  public static final int COLON = 40;
  public static final int ELSE = 58;
  public static final int LSQUARE = 31;
  public static final int RSQUARE = 32;
  public static final int WHILE = 30;
  public static final int PUBLIC = 36;
  public static final int THEN = 28;
  public static final int NE = 9;
  public static final int INITIALIZE = 55;
  public static final int END = 24;
  public static final int UNDERSCORE = 60;
  public static final int STRING = 44;
  public static final int PROC = 27;
  public static final int ODD = 26;
  public static final int GT = 6;
  public static final int VAR = 29;
  public static final int DO = 23;
}

