/* The following code was generated by JFlex 1.4.3 on 5/8/18 9:07 AM */

import java_cup.runtime.SymbolFactory;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 5/8/18 9:07 AM from the specification file
 * <tt>PL0.jflex</tt>
 */
class PL0Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\3\25\0\1\3\7\0\1\12\1\13\1\16\1\14"+
    "\1\6\1\15\1\5\1\17\12\2\1\20\1\4\1\7\1\10\1\11"+
    "\2\0\32\1\6\0\1\27\1\21\1\26\1\34\1\22\1\35\1\23"+
    "\1\41\1\24\2\1\1\30\1\1\1\25\1\31\1\36\1\1\1\37"+
    "\1\32\1\33\1\40\1\42\1\43\3\1\57\0\1\1\12\0\1\1"+
    "\4\0\1\1\5\0\27\1\1\0\37\1\1\0\u01ca\1\4\0\14\1"+
    "\16\0\5\1\7\0\1\1\1\0\1\1\201\0\5\1\1\0\2\1"+
    "\2\0\4\1\10\0\1\1\1\0\3\1\1\0\1\1\1\0\24\1"+
    "\1\0\123\1\1\0\213\1\10\0\236\1\11\0\46\1\2\0\1\1"+
    "\7\0\47\1\110\0\33\1\5\0\3\1\55\0\53\1\25\0\12\2"+
    "\4\0\2\1\1\0\143\1\1\0\1\1\17\0\2\1\7\0\2\1"+
    "\12\2\3\1\2\0\1\1\20\0\1\1\1\0\36\1\35\0\131\1"+
    "\13\0\1\1\16\0\12\2\41\1\11\0\2\1\4\0\1\1\5\0"+
    "\26\1\4\0\1\1\11\0\1\1\3\0\1\1\27\0\31\1\107\0"+
    "\1\1\1\0\13\1\127\0\66\1\3\0\1\1\22\0\1\1\7\0"+
    "\12\1\4\0\12\2\1\0\7\1\1\0\7\1\5\0\10\1\2\0"+
    "\2\1\2\0\26\1\1\0\7\1\1\0\1\1\3\0\4\1\3\0"+
    "\1\1\20\0\1\1\15\0\2\1\1\0\3\1\4\0\12\2\2\1"+
    "\23\0\6\1\4\0\2\1\2\0\26\1\1\0\7\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\37\0\4\1\1\0\1\1\7\0\12\2"+
    "\2\0\3\1\20\0\11\1\1\0\3\1\1\0\26\1\1\0\7\1"+
    "\1\0\2\1\1\0\5\1\3\0\1\1\22\0\1\1\17\0\2\1"+
    "\4\0\12\2\25\0\10\1\2\0\2\1\2\0\26\1\1\0\7\1"+
    "\1\0\2\1\1\0\5\1\3\0\1\1\36\0\2\1\1\0\3\1"+
    "\4\0\12\2\1\0\1\1\21\0\1\1\1\0\6\1\3\0\3\1"+
    "\1\0\4\1\3\0\2\1\1\0\1\1\1\0\2\1\3\0\2\1"+
    "\3\0\3\1\3\0\14\1\26\0\1\1\25\0\12\2\25\0\10\1"+
    "\1\0\3\1\1\0\27\1\1\0\12\1\1\0\5\1\3\0\1\1"+
    "\32\0\2\1\6\0\2\1\4\0\12\2\25\0\10\1\1\0\3\1"+
    "\1\0\27\1\1\0\12\1\1\0\5\1\3\0\1\1\40\0\1\1"+
    "\1\0\2\1\4\0\12\2\1\0\2\1\22\0\10\1\1\0\3\1"+
    "\1\0\51\1\2\0\1\1\20\0\1\1\21\0\2\1\4\0\12\2"+
    "\12\0\6\1\5\0\22\1\3\0\30\1\1\0\11\1\1\0\1\1"+
    "\2\0\7\1\72\0\60\1\1\0\2\1\14\0\7\1\11\0\12\2"+
    "\47\0\2\1\1\0\1\1\2\0\2\1\1\0\1\1\2\0\1\1"+
    "\6\0\4\1\1\0\7\1\1\0\3\1\1\0\1\1\1\0\1\1"+
    "\2\0\2\1\1\0\4\1\1\0\2\1\11\0\1\1\2\0\5\1"+
    "\1\0\1\1\11\0\12\2\2\0\4\1\40\0\1\1\37\0\12\2"+
    "\26\0\10\1\1\0\44\1\33\0\5\1\163\0\53\1\24\0\1\1"+
    "\12\2\6\0\6\1\4\0\4\1\3\0\1\1\3\0\2\1\7\0"+
    "\3\1\4\0\15\1\14\0\1\1\1\0\12\2\6\0\46\1\1\0"+
    "\1\1\5\0\1\1\2\0\53\1\1\0\u014d\1\1\0\4\1\2\0"+
    "\7\1\1\0\1\1\1\0\4\1\2\0\51\1\1\0\4\1\2\0"+
    "\41\1\1\0\4\1\2\0\7\1\1\0\1\1\1\0\4\1\2\0"+
    "\17\1\1\0\71\1\1\0\4\1\2\0\103\1\45\0\20\1\20\0"+
    "\125\1\14\0\u026c\1\2\0\21\1\1\0\32\1\5\0\113\1\25\0"+
    "\15\1\1\0\4\1\16\0\22\1\16\0\22\1\16\0\15\1\1\0"+
    "\3\1\17\0\64\1\43\0\1\1\4\0\1\1\3\0\12\2\46\0"+
    "\12\2\6\0\130\1\10\0\51\1\1\0\1\1\5\0\106\1\12\0"+
    "\35\1\51\0\12\2\36\1\2\0\5\1\13\0\54\1\25\0\7\1"+
    "\10\0\12\2\46\0\27\1\11\0\65\1\53\0\12\2\6\0\12\2"+
    "\15\0\1\1\135\0\57\1\21\0\7\1\4\0\12\2\51\0\36\1"+
    "\15\0\2\1\12\2\54\1\32\0\44\1\34\0\12\2\3\0\3\1"+
    "\12\2\44\1\153\0\4\1\1\0\4\1\3\0\2\1\11\0\300\1"+
    "\100\0\u0116\1\2\0\6\1\2\0\46\1\2\0\6\1\2\0\10\1"+
    "\1\0\1\1\1\0\1\1\1\0\1\1\1\0\37\1\2\0\65\1"+
    "\1\0\7\1\1\0\1\1\3\0\3\1\1\0\7\1\3\0\4\1"+
    "\2\0\6\1\4\0\15\1\5\0\3\1\1\0\7\1\164\0\1\1"+
    "\15\0\1\1\20\0\15\1\145\0\1\1\4\0\1\1\2\0\12\1"+
    "\1\0\1\1\3\0\5\1\6\0\1\1\1\0\1\1\1\0\1\1"+
    "\1\0\4\1\1\0\13\1\2\0\4\1\5\0\5\1\4\0\1\1"+
    "\64\0\2\1\u0a7b\0\57\1\1\0\57\1\1\0\205\1\6\0\4\1"+
    "\3\0\2\1\14\0\46\1\1\0\1\1\5\0\1\1\2\0\70\1"+
    "\7\0\1\1\20\0\27\1\11\0\7\1\1\0\7\1\1\0\7\1"+
    "\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1\1\0\7\1"+
    "\120\0\1\1\u01d5\0\2\1\52\0\5\1\5\0\2\1\4\0\126\1"+
    "\6\0\3\1\1\0\132\1\1\0\4\1\5\0\51\1\3\0\136\1"+
    "\21\0\33\1\65\0\20\1\u0200\0\u19b6\1\112\0\u51cd\1\63\0\u048d\1"+
    "\103\0\56\1\2\0\u010d\1\3\0\20\1\12\2\2\1\24\0\57\1"+
    "\20\0\31\1\10\0\106\1\61\0\11\1\2\0\147\1\2\0\4\1"+
    "\1\0\4\1\14\0\13\1\115\0\12\1\1\0\3\1\1\0\4\1"+
    "\1\0\27\1\35\0\64\1\16\0\62\1\34\0\12\2\30\0\6\1"+
    "\3\0\1\1\4\0\12\2\34\1\12\0\27\1\31\0\35\1\7\0"+
    "\57\1\34\0\1\1\12\2\46\0\51\1\27\0\3\1\1\0\10\1"+
    "\4\0\12\2\6\0\27\1\3\0\1\1\5\0\60\1\1\0\1\1"+
    "\3\0\2\1\2\0\5\1\2\0\1\1\1\0\1\1\30\0\3\1"+
    "\2\0\13\1\7\0\3\1\14\0\6\1\2\0\6\1\2\0\6\1"+
    "\11\0\7\1\1\0\7\1\221\0\43\1\15\0\12\2\6\0\u2ba4\1"+
    "\14\0\27\1\4\0\61\1\u2104\0\u016e\1\2\0\152\1\46\0\7\1"+
    "\14\0\5\1\5\0\1\1\1\0\12\1\1\0\15\1\1\0\5\1"+
    "\1\0\1\1\1\0\2\1\1\0\2\1\1\0\154\1\41\0\u016b\1"+
    "\22\0\100\1\2\0\66\1\50\0\14\1\164\0\5\1\1\0\207\1"+
    "\23\0\12\2\7\0\32\1\6\0\32\1\13\0\131\1\3\0\6\1"+
    "\2\0\6\1\2\0\6\1\2\0\3\1\43\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\10\1\11\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\1\20\1\1\12\2\1\21\1\22\1\23\1\24\2\2"+
    "\1\25\4\2\1\26\4\2\1\27\2\2\1\30\2\2"+
    "\1\31\2\2\1\32\1\2\1\33\2\2\1\34\1\35"+
    "\1\2\1\36\3\2\1\37";

  private static int [] zzUnpackAction() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\44\0\110\0\154\0\44\0\44\0\44\0\44"+
    "\0\220\0\44\0\264\0\44\0\44\0\44\0\44\0\44"+
    "\0\44\0\330\0\374\0\u0120\0\u0144\0\u0168\0\u018c\0\u01b0"+
    "\0\u01d4\0\u01f8\0\u021c\0\u0240\0\44\0\44\0\44\0\44"+
    "\0\u0264\0\u0288\0\110\0\u02ac\0\u02d0\0\u02f4\0\u0318\0\110"+
    "\0\u033c\0\u0360\0\u0384\0\u03a8\0\110\0\u03cc\0\u03f0\0\110"+
    "\0\u0414\0\u0438\0\110\0\u045c\0\u0480\0\110\0\u04a4\0\110"+
    "\0\u04c8\0\u04ec\0\110\0\110\0\u0510\0\110\0\u0534\0\u0558"+
    "\0\u057c\0\110";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\1\14\1\15\1\16\1\17\1\20\1\21"+
    "\1\22\1\23\1\24\1\3\1\25\1\3\1\26\2\3"+
    "\1\27\1\3\1\30\1\31\1\3\1\32\3\3\1\33"+
    "\1\34\45\0\2\3\16\0\23\3\2\0\1\4\51\0"+
    "\1\35\1\36\42\0\1\37\43\0\1\40\34\0\2\3"+
    "\16\0\1\3\1\41\21\3\1\0\2\3\16\0\4\3"+
    "\1\42\16\3\1\0\2\3\16\0\14\3\1\43\6\3"+
    "\1\0\2\3\16\0\6\3\1\44\1\3\1\45\12\3"+
    "\1\0\2\3\16\0\13\3\1\46\7\3\1\0\2\3"+
    "\16\0\20\3\1\47\2\3\1\0\2\3\16\0\10\3"+
    "\1\50\12\3\1\0\2\3\16\0\16\3\1\51\4\3"+
    "\1\0\2\3\16\0\6\3\1\52\14\3\1\0\2\3"+
    "\16\0\20\3\1\53\2\3\1\0\2\3\16\0\2\3"+
    "\1\54\20\3\1\0\2\3\16\0\13\3\1\55\7\3"+
    "\1\0\2\3\16\0\7\3\1\56\13\3\1\0\2\3"+
    "\16\0\4\3\1\57\16\3\1\0\2\3\16\0\13\3"+
    "\1\60\7\3\1\0\2\3\16\0\1\3\1\61\21\3"+
    "\1\0\2\3\16\0\10\3\1\62\12\3\1\0\2\3"+
    "\16\0\16\3\1\63\4\3\1\0\2\3\16\0\3\3"+
    "\1\64\17\3\1\0\2\3\16\0\3\3\1\65\17\3"+
    "\1\0\2\3\16\0\7\3\1\66\13\3\1\0\2\3"+
    "\16\0\11\3\1\67\11\3\1\0\2\3\16\0\4\3"+
    "\1\70\16\3\1\0\2\3\16\0\5\3\1\71\15\3"+
    "\1\0\2\3\16\0\7\3\1\72\13\3\1\0\2\3"+
    "\16\0\4\3\1\73\16\3\1\0\2\3\16\0\12\3"+
    "\1\74\10\3\1\0\2\3\16\0\1\3\1\75\21\3"+
    "\1\0\2\3\16\0\1\3\1\76\21\3\1\0\2\3"+
    "\16\0\13\3\1\77\7\3\1\0\2\3\16\0\17\3"+
    "\1\100\3\3\1\0\2\3\16\0\16\3\1\101\4\3"+
    "\1\0\2\3\16\0\1\3\1\102\21\3";

  private static int [] zzUnpackTrans() {
    int [] result = new int[1440];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\2\1\4\11\1\1\1\11\1\1\6\11"+
    "\13\1\4\11\42\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[66];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  private SymbolFactory symbolFactory;

  public PL0Lexer (java . io . InputStream input, SymbolFactory sf) {
    this (input);
    symbolFactory = sf;
  }

  private void echo () { System . out . print (yytext ()); }

  public int position () { return yycolumn; }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  PL0Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  PL0Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1674) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 5: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, ;)", Symbol . SEMICOLON);
          }
        case 32: break;
        case 21: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, if)", Symbol . IF);
          }
        case 33: break;
        case 28: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, begin)", Symbol . BEGIN);
          }
        case 34: break;
        case 6: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, .)", Symbol . PERIOD);
          }
        case 35: break;
        case 13: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, +)", Symbol . PLUS);
          }
        case 36: break;
        case 2: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(identifier, " + yytext () + ")", 
                      Symbol . ID, yytext ());
          }
        case 37: break;
        case 15: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, *)", Symbol . TIMES);
          }
        case 38: break;
        case 14: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, -)", Symbol . MINUS);
          }
        case 39: break;
        case 18: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <>)", Symbol . NE);
          }
        case 40: break;
        case 12: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, ))", Symbol . RPAREN);
          }
        case 41: break;
        case 20: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, :=)", Symbol . ASSIGN);
          }
        case 42: break;
        case 10: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, >)", Symbol . GT);
          }
        case 43: break;
        case 31: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, procedure)", Symbol . PROC);
          }
        case 44: break;
        case 26: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, end)", Symbol . CALL);
          }
        case 45: break;
        case 1: 
          { echo (); ErrorMessage . print (yychar, "Illegal character");
          }
        case 46: break;
        case 16: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, /)", Symbol . SLASH);
          }
        case 47: break;
        case 9: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, =)", Symbol . EQ);
          }
        case 48: break;
        case 11: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, ()", Symbol . LPAREN);
          }
        case 49: break;
        case 24: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, odd)", Symbol . ODD);
          }
        case 50: break;
        case 23: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, end)", Symbol . END);
          }
        case 51: break;
        case 30: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, while)", Symbol . WHILE);
          }
        case 52: break;
        case 29: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, const)", Symbol . CONST);
          }
        case 53: break;
        case 27: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, then)", Symbol . THEN);
          }
        case 54: break;
        case 7: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(punctuation, ,)", Symbol . COMMA);
          }
        case 55: break;
        case 22: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, do)", Symbol . DO);
          }
        case 56: break;
        case 17: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <=)", Symbol . LE);
          }
        case 57: break;
        case 3: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(integer, " + yytext () + ")", 
                      Symbol . INTEGER, yytext ());
          }
        case 58: break;
        case 19: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, >=)", Symbol . GE);
          }
        case 59: break;
        case 25: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(keyword, var)", Symbol . VAR);
          }
        case 60: break;
        case 4: 
          { echo ();
          }
        case 61: break;
        case 8: 
          { echo (); 
                  return symbolFactory . 
                    newSymbol ("(operator, <)", Symbol . LT);
          }
        case 62: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              {   return symbolFactory . newSymbol ("EOF", Symbol . EOF);
 }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
