
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated interface containing symbol constants. */
public interface Symbol {
  /* terminals */
  public static final int JAVA = 36;
  public static final int GE = 10;
  public static final int SLASH = 16;
  public static final int ARGS = 27;
  public static final int INTEGER = 3;
  public static final int LPAREN = 20;
  public static final int INT = 35;
  public static final int PRINTLN = 41;
  public static final int OUT = 40;
  public static final int MINUS = 14;
  public static final int STATIC = 45;
  public static final int RPAREN = 21;
  public static final int NOT = 6;
  public static final int SEMICOLON = 17;
  public static final int AND = 4;
  public static final int LT = 7;
  public static final int IN = 34;
  public static final int OR = 5;
  public static final int COMMA = 19;
  public static final int CLASS = 29;
  public static final int NEXTINT = 38;
  public static final int PLUS = 13;
  public static final int MAIN = 37;
  public static final int ASSIGN = 26;
  public static final int IF = 32;
  public static final int THIS = 48;
  public static final int DOT = 18;
  public static final int ID = 2;
  public static final int LE = 8;
  public static final int EOF = 0;
  public static final int BOOLEAN = 28;
  public static final int SYSTEM = 47;
  public static final int RETURN = 43;
  public static final int TRUE = 49;
  public static final int NEW = 39;
  public static final int error = 1;
  public static final int UTIL = 50;
  public static final int SCANNER = 44;
  public static final int VOID = 51;
  public static final int EQ = 11;
  public static final int LBRACK = 22;
  public static final int IMPORT = 33;
  public static final int TIMES = 15;
  public static final int LBRACE = 24;
  public static final int ELSE = 30;
  public static final int RBRACK = 23;
  public static final int WHILE = 52;
  public static final int PUBLIC = 42;
  public static final int RBRACE = 25;
  public static final int NE = 12;
  public static final int STRING = 46;
  public static final int FALSE = 31;
  public static final int GT = 9;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "ID",
  "INTEGER",
  "AND",
  "OR",
  "NOT",
  "LT",
  "LE",
  "GT",
  "GE",
  "EQ",
  "NE",
  "PLUS",
  "MINUS",
  "TIMES",
  "SLASH",
  "SEMICOLON",
  "DOT",
  "COMMA",
  "LPAREN",
  "RPAREN",
  "LBRACK",
  "RBRACK",
  "LBRACE",
  "RBRACE",
  "ASSIGN",
  "ARGS",
  "BOOLEAN",
  "CLASS",
  "ELSE",
  "FALSE",
  "IF",
  "IMPORT",
  "IN",
  "INT",
  "JAVA",
  "MAIN",
  "NEXTINT",
  "NEW",
  "OUT",
  "PRINTLN",
  "PUBLIC",
  "RETURN",
  "SCANNER",
  "STATIC",
  "STRING",
  "SYSTEM",
  "THIS",
  "TRUE",
  "UTIL",
  "VOID",
  "WHILE"
  };
}

